### ISSUE TITLE
Doesn't work on vim8

### ISSUE THREAD

**Issue by mattn** [djdt/pyparens.nvim#11]

**Comment by djdt** [comment]
Can you send me any details about this (error messages etc.). I cant reproduce it.

**Comment by mattn** [comment]
I use vim8.0.1010 on Windows. The error bring up on startup of vim.

```
ModuleNotFoundError: No module named 'neovim'
```

**Comment by mattn** [comment]
I could build neovim module on Windows. neovim module is depend greenlet. it can't build on mingw compiler

https://github.com/python-greenlet/greenlet/issues/20

**Comment by mattn** [comment]
However, I wonder why vim8 require neovim module.
