### ISSUE TITLE
Error on startup if native matchParen is disabled

### ISSUE THREAD

**Issue by sunjon** [djdt/pyparens.nvim#4]
I  commonly disable some built-in  plugins  using:
let g:loaded_matchparen = 1

This causes an error on startup due the this plugin trying to disable it itself:
> " Disable matchparen
> if exists("g:loaded_matchparen")
> exec NoMatchParen

**Comment by djdt** [comment]
I switched it to check for the NoMatchParen command. Unsure if there is a better way to make sure matchparen doesn't get loaded / is off if it is loaded.
