### ISSUE TITLE
Variables usage

### ISSUE THREAD

**Issue by sunjon** [djdt/pyparens.nvim#6]
Could you reconsider how you read g:variables that have to be defined before the plugin loads? Usually this is used for g:disable_mappings initialisation variables; others commonly respect on the fly changes.

**Comment by djdt** [comment]
I'll have to look into it, but sure.

**Comment by djdt** [comment]
The variables should reload when you switch to a new window, if you need to reload them straight away you could `call pyparens#init()`.
Does this solve the issue?
