### ISSUE TITLE
Ignore vim fold markers

### ISSUE THREAD

**Issue by sunjon** [djdt/pyparens.nvim#7]
I'd like the ability to have highliting enabled for { parens, but not have it trigger on {{{ patterns.

Edit: just thought this can probably be done with a better regex in my pairs definitions. I'll close this shortly and leave an example of that's the case.

**Comment by djdt** [comment]
This should be solvable using the correct regex, using something like `['(?<!\{)\{(?!\{)', '\}']`.
However, I'm not sure if this should be the default setting.

**Comment by sunjon** [comment]
Perfect.
Yes, some people may want fold markers highlighting for some reason, so I wouldn't have that as a default.
I did adjust all of the expressions to not match empty parents, as it makes vertical bar cursors impossible to see, I would reccomend having that as default.
